Add a few tests
JetBrains-Research/litmuskt pull request #17
Opened 2024-05-08 14:17 UTC by DLochmelis33

2024-05-29 11:01 UTC, eupp requested changes

2024-05-29 11:01 UTC, eupp commented on core/src/commonMain/kotlin/org/jetbrains/litmuskt/autooutcomes/BooleanAutoOutcomes.kt
> +open class LitmusZZOutcome(
Why not `LitmusBBOutcome` ?

2024-05-29 11:01 UTC, eupp commented on core/src/commonMain/kotlin/org/jetbrains/litmuskt/autooutcomes/BooleanAutoOutcomes.kt
> +    final override fun hashCode() = (if (r1) 1 else 0) + (if (r2) 2 else 3)
Consider extracting `if (b) 1 else 0` into `Boolean.toInt()` function.

2024-05-29 11:01 UTC, eupp commented on testsuite/build.gradle.kts
> +//}
Please either restore the commented code, or remove it completely : )

2024-05-29 11:01 UTC, eupp commented on testsuite/src/commonMain/kotlin/org/jetbrains/litmuskt/tests/ArrayVolatile.kt
> +    val vol = litmusTest({
Why it is called `volatile` if there are not volatiles involved here?

2024-05-29 11:01 UTC, eupp commented on testsuite/src/commonMain/kotlin/org/jetbrains/litmuskt/tests/CoRR.kt
> +import org.jetbrains.litmuskt.litmusTest
What about `import org.jetbrains.litmuskt.*` ?

2024-05-29 11:01 UTC, eupp commented on testsuite/src/commonMain/kotlin/org/jetbrains/litmuskt/tests/WordTearing.kt
> +            this
Why do you need `this` at the end?

2024-06-05 12:06 UTC, DLochmelis33 commented on core/src/commonMain/kotlin/org/jetbrains/litmuskt/autooutcomes/BooleanAutoOutcomes.kt
> +open class LitmusZZOutcome(
For consistency with [jcstress](https://github.com/openjdk/jcstress/blob/d6a81c3dbde87d22b24a9bb05205883122b9ecf2/jcstress-samples/src/main/java/org/openjdk/jcstress/samples/jmm/basic/BasicJMM_03_WordTearing.java#L28). `B` there is for `Byte`

2024-06-05 12:08 UTC, DLochmelis33 commented on core/src/commonMain/kotlin/org/jetbrains/litmuskt/autooutcomes/BooleanAutoOutcomes.kt
> +    final override fun hashCode() = (if (r1) 1 else 0) + (if (r2) 2 else 3)
Apparently there's no such thing as `Boolean.toInt()` :thinking:

2024-06-05 12:11 UTC, DLochmelis33 commented on testsuite/src/commonMain/kotlin/org/jetbrains/litmuskt/tests/ArrayVolatile.kt
> +    val vol = litmusTest({
Forgot to add one, fixed

2024-06-05 12:13 UTC, DLochmelis33 commented on testsuite/src/commonMain/kotlin/org/jetbrains/litmuskt/tests/CoRR.kt
> +import org.jetbrains.litmuskt.litmusTest
Makes sense, but then many guidelines recommend never using star-imports at all, and IDEA automatically writes and then folds these imports, so... why not?)

2024-06-05 12:15 UTC, DLochmelis33 commented on testsuite/src/commonMain/kotlin/org/jetbrains/litmuskt/tests/WordTearing.kt
> +            this
`outcome{}` must return the outcome object, and in case with `LitmusAutoOutcome` it's the state itself. This probably has to go into README as an example of how to do jcstress-style "arbiter" functionality

2024-06-21 11:05 UTC, DLochmelis33 commented
Merged manually into `development`

2024-06-21 11:05 UTC, closed without merging